# define a workflow to publish the npm package to GitHUb Packages
# invoke on workflow_dispatch event
# note: modify registry URL with your GitHub Package registry URL

name: Publish NPM package to GitHub Packages

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/ambilykk-demo-org
      - run: npm install
      - run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
